_BASE_: "../ALDI-Best-Sim10k.yaml"
MODEL:
  WEIGHTS: "models/sim10k_baseline_imagenet_strongaug_ema_cityscapes_cars_val_model_best_614.pth"
SOLVER:
  BASE_LR: 0.01
  STEPS: (49999,)
  MAX_ITER: 50000
OUTPUT_DIR: "output/sim10k/sim10k_aldi_best_imagenet/"
