_BASE_: "../Base-RCNN-FPN-Sim10k_strongaug_ema.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
SOLVER:
  BASE_LR: 0.01
  STEPS: (15999,)
  MAX_ITER: 16000
OUTPUT_DIR: "output/sim10k/sim10k_baseline_imagenet_strongaug_ema/"
