_BASE_: "../Base-RCNN-FPN-Cityscapes_strongaug_ema.yaml"
MODEL:
  WEIGHTS: "models/cityscapes_baseline_imagenet_strongaug_ema_foggy_val_model_best_519.pth"
EMA:
  ENABLED: True
DOMAIN_ADAPT:
  TEACHER:
    ENABLED: True
  DISTILL:
    HARD_ROIH_CLS_ENABLED: False
    HARD_ROIH_REG_ENABLED: False
    HARD_OBJ_ENABLED: False
    HARD_RPN_REG_ENABLED: False
    ROIH_CLS_ENABLED: True
    OBJ_ENABLED: True
    ROIH_REG_ENABLED: True
    RPN_REG_ENABLED: True
AUG:
  LABELED_INCLUDE_RANDOM_ERASING: True
  UNLABELED_INCLUDE_RANDOM_ERASING: False
  LABELED_MIC_AUG: False
  UNLABELED_MIC_AUG: True
DATASETS:
  UNLABELED: ("cityscapes_foggy_train",)
  BATCH_CONTENTS: ("labeled_strong", "unlabeled_strong")
  BATCH_RATIOS: (1,1)
SOLVER:
  BASE_LR: 0.01
  STEPS: (49999,)
  MAX_ITER: 50000
  BACKWARD_AT_END: False
OUTPUT_DIR: "output/cityscapes/cityscapes_aldi_best_imagenet/"
