_BASE_: "../cityscapes_priorart/AT-Cityscapes.yaml"
MODEL:
  WEIGHTS: "models/cityscapes_baseline_imagenet_foggy_val_model_best_437.pth"
SOLVER:
  # BASE_LR: 0.01
  STEPS: (49999,)
  MAX_ITER: 50000
OUTPUT_DIR: "output/cityscapes_at_imagenet/"