_BASE_: "../Base-RCNN-FPN-Cityscapes.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
SOLVER:
  BASE_LR: 0.01 # diverges with 0.06
  STEPS: (9999,)
  MAX_ITER: 10000
OUTPUT_DIR: "output/cityscapes/cityscapes_baseline_imagenet/"