_BASE_: "../cityscapes_priorart/MIC-Cityscapes.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
SOLVER:
  BASE_LR: 0.01 # diverges with 0.06
EMA:
  ALPHA: 0.9
OUTPUT_DIR: "output/cityscapes_mic_imagenet_alpha09_sadabug/"
