_BASE_: "../OracleT-RCNN-FPN-Cityscapes_strongaug_ema.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
SOLVER:
  BASE_LR: 0.01
  STEPS: (19999,)
  MAX_ITER: 20000
OUTPUT_DIR: "output/cityscapes/cityscapes_oracle-t_strongaug_ema_imagenet/"
