_BASE_: "../MeanTeacher-Cityscapes.yaml"
MODEL:
  WEIGHTS: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
SOLVER:
  STEPS: (99999,)
  MAX_ITER: 100000
OUTPUT_DIR: "output/cityscapes_meanteacher_noburnin/"