_BASE_: "../Base-RCNN-VitDetB.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 8
DATASETS:
  TRAIN: ("cityscapes_train",)
  TEST: ("cityscapes_val", "cityscapes_foggy_val",)
  BATCH_CONTENTS: ("labeled_strong", )
EMA:
  ENABLED: True
SOLVER:
  STEPS: (6400,)
  MAX_ITER: 8000
OUTPUT_DIR: "output/cityscapes/cityscapes_vitdetb_baseline_strongaug_ema/"