_BASE_: "./Base-RCNN-VitDetB-Cityscapes.yaml"
DATASETS:
  TRAIN: ("cityscapes_foggy_train",)
  TEST: ("cityscapes_val","cityscapes_foggy_val",)
  BATCH_CONTENTS: ("labeled_strong", )
EMA:
  ENABLED: True
SOLVER:
  STEPS: (6400,)
  MAX_ITER: 8000
OUTPUT_DIR: "output/cityscapes/cityscapes_vitdetb_oracle-t_strongaug_ema/"