_BASE_: "./Base-Yolo-Cityscapes_strongaug_ema.yaml"
MODEL:
  WEIGHTS: "models/cityscapes_yolo_baseline_strongaug_ema_foggy_val_model_best_611.pth"
EMA:
  ENABLED: True
DOMAIN_ADAPT:
  TEACHER:
    ENABLED: True
  DISTILL:
    HARD_ROIH_CLS_ENABLED: False
    HARD_ROIH_REG_ENABLED: False
    HARD_OBJ_ENABLED: False
    HARD_RPN_REG_ENABLED: False # N/A for YOLO
    ROIH_CLS_ENABLED: True 
    OBJ_ENABLED: True 
    ROIH_REG_ENABLED: True 
    RPN_REG_ENABLED: False # N/A for YOLO
AUG:
  LABELED_INCLUDE_RANDOM_ERASING: True
  UNLABELED_INCLUDE_RANDOM_ERASING: False
  LABELED_MIC_AUG: False
  UNLABELED_MIC_AUG: True
DATASETS:
  UNLABELED: ("cityscapes_foggy_train",)
  BATCH_CONTENTS: ("labeled_strong", "unlabeled_strong")
  BATCH_RATIOS: (1,1)
OUTPUT_DIR: "output/cityscapes/cityscapes_aldi_yolo/"