_BASE_: "../Base-RCNN-ConvNeXt-FPN.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 8
DATASETS:
  TRAIN: ("cityscapes_train",)
  TEST: ("cityscapes_foggy_val",)
  BATCH_CONTENTS: ("labeled_strong", )
EMA:
  ENABLED: True
SOLVER:
  BASE_LR: 0.02
  STEPS: (9999,)
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 100
OUTPUT_DIR: "output/cityscapes/cityscapes_convnext_baseline_strongaug_ema/"
