_BASE_: "../Base-DETR.yaml"
MODEL:
  DEFORMABLE_DETR:
    NUM_CLASSES: 8
DATASETS:
  TRAIN: ("cityscapes_train",)
  TEST: ("cityscapes_val", "cityscapes_foggy_val",)
  BATCH_CONTENTS: ("labeled_strong", )
EMA:
  ENABLED: True
SOLVER:
  STEPS: (9999,)
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 100
OUTPUT_DIR: "output/cityscapes/cityscapes_baseline_detr_coco_strongaug_ema/"
EMA:
  START_ITER: 1500