_BASE_: "./Base-RCNN-ConvNeXt-FPN-Cityscapes_strongaug_ema.yaml"
DATASETS:
  TRAIN: ("cityscapes_foggy_train",)
  TEST: ("cityscapes_foggy_val",)
  BATCH_CONTENTS: ("labeled_strong", )
EMA:
  ENABLED: True
OUTPUT_DIR: "output/cityscapes/cityscapes_oracle-t_convnext_strongaug_ema/"