_BASE_: "../../Base-RCNN-VitDetB.yaml"
MODEL:
  FSDP_ENABLED: False # it's big -- but this doesn't work yet
  ROI_HEADS:
    NUM_CLASSES: 8
DATASETS:
  TRAIN: ("cityscapes_train",)
  TEST: ("cityscapes_val", "cityscapes_foggy_val",)
OUTPUT_DIR: "output/cityscapes_vitdetb_baseline/"