_BASE_: "../../Base-RCNN-VGG16.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 8
DATASETS:
  TRAIN: ("cityscapes_train",)
  TEST: ("cityscapes_val", "cityscapes_foggy_val",)
OUTPUT_DIR: "output/cityscapes_baseline_vgg16/"