_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "models/R-50.pkl"
  ROI_HEADS:
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("sim10k_cars_train",)
  TEST: ("cityscapes_cars_val",)
OUTPUT_DIR: "output/sim10k/sim10k_baseline_imagenet/"

SOLVER:
  STEPS: (2600,) 
  MAX_ITER: 3000 # 15 epochs
TEST:
  EVAL_PERIOD: 200