_BASE_: "../Base-RCNN-VitDetB.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("sim10k_cars_train",)
  TEST: ("cityscapes_cars_val",)
  BATCH_CONTENTS: ("labeled_strong", )
EMA:
  ENABLED: True
SOLVER:
  STEPS: (2999,)
  MAX_ITER: 3000
  CHECKPOINT_PERIOD: 1000
TEST:
  EVAL_PERIOD: 100
OUTPUT_DIR: "output/sim10k/sim10k_vitdetb_baseline_strongaug_ema/"

