_BASE_: "../Base-RCNN-FPN-CFC.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
SOLVER:
  BASE_LR: 0.01 
  STEPS: (14999,)
  MAX_ITER: 15000
OUTPUT_DIR: "output/cfc/cfc_baseline_imagenet/"