_BASE_: "../cfc_priorart/MIC-CFC_NoBurnIn.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
SOLVER:
  BASE_LR: 0.005
DATASETS:
  TEST: ("cfc_channel_test",)
OUTPUT_DIR: "output/cfc/cfc_mic_imagenet_alpha09_2/"
