_BASE_: "./AT-Cityscapes.yaml"
MODEL:
  CMT:
    ENABLED: True
    CONTRASTIVE_LOSS_WEIGHT: 0.01
SOLVER:
  IMS_PER_BATCH: 48
  IMS_PER_GPU: 2
  BACKWARD_AT_END: True
INPUT:
  MIN_SIZE_TRAIN: (1024,)  # TODO: currently need identical image sizes inside a single batch to enable CMT
OUTPUT_DIR: "output/cityscapes_cmtat/"