MODEL:
  META_ARCHITECTURE: Yolo
  YAML: yolov5://yolov5m.yaml
  YOLO:
    FOCAL_LOSS_GAMMA: 0.0
    BOX_LOSS_GAIN: 0.05
    CLS_LOSS_GAIN: 0.3
    CLS_POSITIVE_WEIGHT: 1.0
    OBJ_LOSS_GAIN: 0.7
    OBJ_POSITIVE_WEIGHT: 1.0
    LABEL_SMOOTHING: 0.0
    ANCHOR_T: 4.0
    CONF_THRESH: 0.001
    IOU_THRES: 0.65
    NUM_CLASSES: 8
  PIXEL_MEAN: [0.0, 0.0, 0.0]
  PIXEL_STD: [255.0, 255.0, 255.0]
  WEIGHTS: "models/yolov5m_detectron2.pt"
  MASK_ON: False
SOLVER:
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_BIAS: 0.0001
  IMS_PER_BATCH: 48
  IMS_PER_GPU: 12
  BASE_LR: 0.03  # three times the effective batch size times original lr of 0.01
  MAX_ITER: 50000
  LR_SCHEDULER_NAME: WarmupCosineLR
  WARMUP_ITERS: 2500
  BACKWARD_AT_END: False
  AMP:
    ENABLED: True
  CHECKPOINT_PERIOD: 1000
INPUT:
  FORMAT: RGB
  MIN_SIZE_TRAIN: (800, 832, 864, 896, 928, 960, 992, 1024)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 2048
  MAX_SIZE_TEST: 2048
DOMAIN_ADAPT:
  DISTILL:
    DISTILLER_NAME: YoloDistiller
    MIXIN_NAME: YoloDistillMixin
  ALIGN:
    MIXIN_NAME: YoloAlignMixin
TEST:
  AUG:
    ENABLED: False
VIS_PERIOD: 1000
TEST:
  EVAL_PERIOD: 1000