MODEL:
  META_ARCHITECTURE: "DeformableDETR"
  # WEIGHTS: "models/r50_deformable_detr-checkpoint-converted.pth" # 
  WEIGHTS: "" # Pre-trained ImageNet weights auto-loaded from torchvision in the code
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  DEFORMABLE_DETR:
    NUM_CLASSES: 80
    BACKBONE: 'resnet50'
    DILATION: False
    POSITION_EMBEDDING: 'sine' # sine or learned
    POSITION_EMBEDDING_SCALE: 6.283185307179586 # 2*np.pi
    NUM_FEATURE_LEVELS: 4
    # Variants of Deformable DETR
    WITH_BOX_REFINE: False
    TWO_STAGE: False
    TRANSFORMER:
      NUM_QUERIES: 300
      ENC_LAYERS: 6
      DEC_LAYERS: 6
      NHEADS: 8
      DIM_FEEDFORWARD: 1024
      HIDDEN_DIM: 256
      DROPOUT: 0.1
      DEC_N_POINTS: 4
      ENC_N_POINTS: 4
    LOSS:
      AUX_LOSS: True
      MASK_LOSS_COEF: 1.0
      DICE_LOSS_COEF: 1.0
      CLS_LOSS_COEF: 2.0
      BBOX_LOSS_COEF: 5.0
      GIOU_LOSS_COEF: 2.0
      FOCAL_ALPHA: 0.25
    MATCHER:
      SET_COST_CLASS: 2
      SET_COST_BBOX: 5
      SET_COST_GIOU: 2
    FROZEN_WEIGHTS: False # For segmentation
  MASK_ON: False
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800) # match other DETR domain adaptation papers
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  FORMAT: "RGB"
SOLVER:
  # BASE_LR: 0.06
  BASE_LR: 0.0001
  STEPS: (1600,)
  MAX_ITER: 2000
  IMS_PER_BATCH: 48
  IMS_PER_GPU: 16
  BACKWARD_AT_END: False
  AMP:
    ENABLED: False # not supported for multiscale deformable conv
  WARMUP_ITERS: 100
  WARMUP_FACTOR: 0.01
  CHECKPOINT_PERIOD: 500
  OPTIMIZER: "ADAMW"
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.1
    NORM_TYPE: 2.0
  BACKBONE_LR_MULTIPLIER: 0.1
  LR_BACKBONE_NAMES: ["backbone.0"]
  LR_LINEAR_PROJ_NAMES: ['reference_points', 'sampling_offsets']
  LR_LINEAR_PROJ_MULTIPLIER: 0.1
VIS_PERIOD: 100
TEST:
  EVAL_PERIOD: 100
EMA:
  START_ITER: 250 # to speed up training ; assuming 2 GPUS ~= 10 epochs
DOMAIN_ADAPT:
  DISTILL:
    DISTILLER_NAME: HardDistiller
    MIXIN_NAME: DETRDistillMixin
  ALIGN:
    MIXIN_NAME: DETRAlignMixin