_BASE_: "./cfc_baseline/Base-RCNN-VitDetB-CFC.yaml"
MODEL:
  WEIGHTS: "models/cfc_vitdetb_channel_test_model_best_strongaug_ema_690_ema2model.pth"
EMA:
  ENABLED: True
DATASETS:
  UNLABELED: ("cfc_channel_train",)
  BATCH_CONTENTS: ("labeled_weak", "labeled_strong", "unlabeled_strong")
  BATCH_RATIOS: (1,1,1)
DOMAIN_ADAPT:
  TEACHER:
    ENABLED: True
  DISTILL:
    # By default, disable localization losses (done by AT, UBT, MIC, ...)
    HARD_ROIH_CLS_ENABLED: True
    HARD_ROIH_REG_ENABLED: False
    HARD_OBJ_ENABLED: True
    HARD_RPN_REG_ENABLED: False
SOLVER:
  STEPS: (59999,)
  MAX_ITER: 60000
  BACKWARD_AT_END: False
OUTPUT_DIR: "output/cfc_vitdetb_meanteacher/"