_BASE_: "../MeanTeacher-Cityscapes.yaml"
AUG:
  LABELED_INCLUDE_RANDOM_ERASING: False
  UNLABELED_INCLUDE_RANDOM_ERASING: False
  LABELED_MIC_AUG: True
  UNLABELED_MIC_AUG: True
OUTPUT_DIR: "output/cityscapes_meanteacher_MICaug/"