_BASE_: "../MeanTeacher-Cityscapes.yaml"
AUG:
  LABELED_INCLUDE_RANDOM_ERASING: True
  UNLABELED_INCLUDE_RANDOM_ERASING: True
  LABELED_MIC_AUG: True
  UNLABELED_MIC_AUG: True
OUTPUT_DIR: "output/cityscapes/cityscapes_meanteacher_MICaug_and_randomerase/"