_BASE_: "../MeanTeacher-Sim10k.yaml"
MODEL:
  WEIGHTS: "models/sim10k_baseline_cityscapes_cars_val_model_best_687.pth"
  META_ARCHITECTURE: "ExtraRCNN"
DATASETS:
  BATCH_CONTENTS: ("labeled_weak", "unlabeled_strong")
  BATCH_RATIOS: (1,1)
AUG:
  LABELED_INCLUDE_RANDOM_ERASING: False
  UNLABELED_INCLUDE_RANDOM_ERASING: False
  UNLABELED_MIC_AUG: True
DOMAIN_ADAPT:
  LOSSES:
    QUALITY_LOSS_WEIGHT_ENABLED: True
  ALIGN:
    SADA_ENABLED: True
SOLVER:
  STEPS: (49999,)
  MAX_ITER: 50000
TEST:
  EVAL_PERIOD: 100
OUTPUT_DIR: "output/sim10k_mic/"