_BASE_: "../Base-RCNN-FPN-Sim10k_strongaug_ema.yaml"
EMA:
  ENABLED: False
DOMAIN_ADAPT:
  ALIGN:
    SADA_ENABLED: True
DATASETS:
  UNLABELED: ("cityscapes_cars_train",)
  BATCH_CONTENTS: ("labeled_weak","unlabeled_weak")
  BATCH_RATIOS: (1,1)
TEST:
  EVAL_PERIOD: 25 
OUTPUT_DIR: "output/sim10k/sim10k_sada_weakaug/"
