_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  BACKBONE:
    NAME: "build_vitdet_b_backbone"
  WEIGHTS: "models/model_final_61ccd1.pkl"
## See detectron2/configs/common/models/mask_rcnn_vitdet.py
  ROI_BOX_HEAD:
    NORM: "LN"
    CONV_DIM: 256
    NUM_CONV: 4
    FC_DIM: 1024
    NUM_FC: 1
  RPN:
    CONV_DIMS: [-1, -1]
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.12, 57.375]
INPUT:
  FORMAT: "RGB"
SOLVER:
  IMS_PER_BATCH: 48
  IMS_PER_GPU: 1
  STEPS: (3200,)
  MAX_ITER: 4000
  OPTIMIZER: "ADAMW"
  BASE_LR: 0.0001
VIT:
  USE_ACT_CHECKPOINT: True